apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170116240
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/okzx5ykc-tenant/test-app-170116240/java-quarkus-170116240@sha256:2dd5398e1ec5a812cb0dfeefb8d55c796032caaea9c16578c2469b9830a30516
        name: my-java-quarkus
        resources: {}
status: {}
